osx_image: xcode8
language: objective-c
before_script:
    - brew update
    - brew install carthage || true
    - brew upgrade carthage || true
    - carthage bootstrap --platform macOS
    - curl -L http://spread-beaver.herokuapp.com/
script: xcodebuild -scheme MusicFeeder-macOS test
